#!/bin/bash
# /etc/init.d/monitoring-agent
# Script to start the monitoring-agent daemon

### BEGIN INIT INFO
# Provides:          monitoring-agent
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start monitoring-agent at boot time
# Description:       ...
### END INIT INFO

conf="/etc/monitoring-agent/config.toml"
prog=monitoring-agent
binary="/usr/bin/monitoring-agent"
pidfile="/var/run/${prog}.pid"

if [ `id -u` -ne 0 ]; then
        echo "You need root privileges to run this script"
        exit 1
fi

#start exporter
start(){
	echo -n "Starting "
        command="$binary"
        $command &
        echo $! > $pidfile
}

#stop exporter
stop(){
        echo -n $"Stopping $prog "
	echo $pidfile
        if [ -f "$pidfile" ]
        then
  	      kill -9 $(cat $pidfile)
              [ $? -eq 0 ] && echo " [ OK ] " || echo " [ FAILED ] "
              [ -f "$pidfile" ] && rm -f "$pidfile"
              # kill -9 $(ps -ef | grep $binary | grep -v grep | awk '{print $2}')
	fi
}


status(){
        if [ -f "$pidfile" ]
        then
                statusCode=$(ps -ef | grep $(cat $pidfile) | grep -v grep | wc -l)
                if [ $statusCode -eq 1 ]
                then
                        echo "Running"
                        exit 0
                else
                        echo "Not running"
                        exit 1
                fi
        else
                echo "Not Running"
                exit 1
        fi
}


case "$1" in
        start)
                start 
                ;;
        stop)
                stop 
                ;;
        restart)
                stop
                start
                ;;
        status)
                status
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart|status}" 
esac